#pragma once

// StraightLineMovementComponent.hpp — C++ port of
// Elements/General/StraightLineMovementComponent.cs (XNA 4.0 NinjAcademy
// sample). A component that moves between two points in a straight line at
// a specified speed.

#include <functional>
#include <stdexcept>

#include "Microsoft/Xna/Framework/Graphics/SpriteEffects.hpp"
#include "System/TimeSpan.hpp"

#include "AnimatedComponent.hpp"

namespace NinjAcademy {

using Microsoft::Xna::Framework::Graphics::SpriteEffects;

// Port of Elements/General/StraightLineMovementComponent.cs.
class StraightLineMovementComponent : public AnimatedComponent {
public:
    // Fired once the component has reached its destination. Fires only once per call of Move().
    std::function<void()> FinishedMoving;

    StraightLineMovementComponent(Game& game, GameScreen* gameScreen, Texture2D texture)
        : AnimatedComponent(game, gameScreen, std::move(texture)) {}

    StraightLineMovementComponent(Game& game, GameScreen* gameScreen, Animation animation)
        : AnimatedComponent(game, gameScreen, std::move(animation)) {}

    Vector2 Center() const override { return Position; }

    void Update(GameTime& gameTime) override {
        AnimatedComponent::Update(gameTime);

        float elapsedSeconds = (float)gameTime.getElapsedGameTimeProperty().getTotalSecondsProperty();

        Vector2 movement = velocity_ * elapsedSeconds;
        Position = Position + movement;
        distance_ -= movement.Length();

        // Check whether the event generated by reaching the destination needs to be fired.
        if (!isEventFired_ && distance_ <= 0.0f) {
            // Move back in case we moved too much.
            velocity_.Normalize();
            Position = Position + velocity_ * distance_;

            if (FinishedMoving)
                FinishedMoving();

            isEventFired_ = true;
            velocity_ = Vector2::Zero;
        }
    }

    void Draw(const GameTime& gameTime) override {
        (void)gameTime;
        spriteBatch_->Begin();
        animation_.Draw(*spriteBatch_, Position, 0.0f, VisualCenter, 1.0f, SpriteEffects::None, 0.0f);
        spriteBatch_->End();
    }

    // Moves from initialPosition to destination at a specified speed (pixels/second, must be > 0).
    void Move(float velocity, Vector2 initialPosition, Vector2 destination) {
        if (velocity <= 0.0f) {
            throw std::out_of_range("velocity must be greater than 0.");
        }

        Vector2 toDestinationVector = destination - initialPosition;
        Vector2 velocityUnitVector = toDestinationVector;
        velocityUnitVector.Normalize();

        velocity_ = velocityUnitVector * velocity;
        distance_ = toDestinationVector.Length();
        Position = initialPosition;
        isEventFired_ = false;
    }

    // Moves from initialPosition to destination over a specified (positive) duration.
    void Move(System::TimeSpan time, Vector2 initialPosition, Vector2 destination) {
        if (time <= System::TimeSpan::Zero) {
            throw std::out_of_range("time must be a positive time span.");
        }

        Vector2 toDestinationVector = destination - initialPosition;
        float distance = toDestinationVector.Length();

        float requiredVelocity = distance / (float)time.getTotalSecondsProperty();

        Move(requiredVelocity, initialPosition, destination);
    }

protected:
    Vector2 velocity_;
    float distance_ = 0.0f;

private:
    bool isEventFired_ = true;
};

} // namespace NinjAcademy
